# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bpfmap-data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bpfmap-data.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x62pfmap-data.proto\"\\\n\x11\x62pfmap_data_entry\x12\x0e\n\x06map_id\x18\x01 \x02(\r\x12\x12\n\nkeys_bytes\x18\x02 \x02(\r\x12\x14\n\x0cvalues_bytes\x18\x03 \x02(\r\x12\r\n\x05\x63ount\x18\x04 \x02(\r'
)




_BPFMAP_DATA_ENTRY = _descriptor.Descriptor(
  name='bpfmap_data_entry',
  full_name='bpfmap_data_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_id', full_name='bpfmap_data_entry.map_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys_bytes', full_name='bpfmap_data_entry.keys_bytes', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values_bytes', full_name='bpfmap_data_entry.values_bytes', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='bpfmap_data_entry.count', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['bpfmap_data_entry'] = _BPFMAP_DATA_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

bpfmap_data_entry = _reflection.GeneratedProtocolMessageType('bpfmap_data_entry', (_message.Message,), {
  'DESCRIPTOR' : _BPFMAP_DATA_ENTRY,
  '__module__' : 'bpfmap_data_pb2'
  # @@protoc_insertion_point(class_scope:bpfmap_data_entry)
  })
_sym_db.RegisterMessage(bpfmap_data_entry)


# @@protoc_insertion_point(module_scope)
