# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipc-msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ipc_desc_pb2 as ipc__desc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ipc-msg.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ripc-msg.proto\x1a\x0eipc-desc.proto\"\'\n\x07ipc_msg\x12\r\n\x05mtype\x18\x01 \x02(\x04\x12\r\n\x05msize\x18\x02 \x02(\r\"L\n\ripc_msg_entry\x12\x1d\n\x04\x64\x65sc\x18\x01 \x02(\x0b\x32\x0f.ipc_desc_entry\x12\x0e\n\x06qbytes\x18\x02 \x02(\r\x12\x0c\n\x04qnum\x18\x03 \x02(\r'
  ,
  dependencies=[ipc__desc__pb2.DESCRIPTOR,])




_IPC_MSG = _descriptor.Descriptor(
  name='ipc_msg',
  full_name='ipc_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mtype', full_name='ipc_msg.mtype', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msize', full_name='ipc_msg.msize', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=72,
)


_IPC_MSG_ENTRY = _descriptor.Descriptor(
  name='ipc_msg_entry',
  full_name='ipc_msg_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='desc', full_name='ipc_msg_entry.desc', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qbytes', full_name='ipc_msg_entry.qbytes', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qnum', full_name='ipc_msg_entry.qnum', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=150,
)

_IPC_MSG_ENTRY.fields_by_name['desc'].message_type = ipc__desc__pb2._IPC_DESC_ENTRY
DESCRIPTOR.message_types_by_name['ipc_msg'] = _IPC_MSG
DESCRIPTOR.message_types_by_name['ipc_msg_entry'] = _IPC_MSG_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ipc_msg = _reflection.GeneratedProtocolMessageType('ipc_msg', (_message.Message,), {
  'DESCRIPTOR' : _IPC_MSG,
  '__module__' : 'ipc_msg_pb2'
  # @@protoc_insertion_point(class_scope:ipc_msg)
  })
_sym_db.RegisterMessage(ipc_msg)

ipc_msg_entry = _reflection.GeneratedProtocolMessageType('ipc_msg_entry', (_message.Message,), {
  'DESCRIPTOR' : _IPC_MSG_ENTRY,
  '__module__' : 'ipc_msg_pb2'
  # @@protoc_insertion_point(class_scope:ipc_msg_entry)
  })
_sym_db.RegisterMessage(ipc_msg_entry)


# @@protoc_insertion_point(module_scope)
