# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fs.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08\x66s.proto\":\n\x08\x66s_entry\x12\x0e\n\x06\x63wd_id\x18\x01 \x02(\r\x12\x0f\n\x07root_id\x18\x02 \x02(\r\x12\r\n\x05umask\x18\x03 \x01(\r'
)




_FS_ENTRY = _descriptor.Descriptor(
  name='fs_entry',
  full_name='fs_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cwd_id', full_name='fs_entry.cwd_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root_id', full_name='fs_entry.root_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='umask', full_name='fs_entry.umask', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['fs_entry'] = _FS_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

fs_entry = _reflection.GeneratedProtocolMessageType('fs_entry', (_message.Message,), {
  'DESCRIPTOR' : _FS_ENTRY,
  '__module__' : 'fs_pb2'
  # @@protoc_insertion_point(class_scope:fs_entry)
  })
_sym_db.RegisterMessage(fs_entry)


# @@protoc_insertion_point(module_scope)
