# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: img-streamer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='img-streamer.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12img-streamer.proto\".\n\x1aimg_streamer_request_entry\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\"*\n\x18img_streamer_reply_entry\x12\x0e\n\x06\x65xists\x18\x01 \x02(\x08'
)




_IMG_STREAMER_REQUEST_ENTRY = _descriptor.Descriptor(
  name='img_streamer_request_entry',
  full_name='img_streamer_request_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='img_streamer_request_entry.filename', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=68,
)


_IMG_STREAMER_REPLY_ENTRY = _descriptor.Descriptor(
  name='img_streamer_reply_entry',
  full_name='img_streamer_reply_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='img_streamer_reply_entry.exists', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['img_streamer_request_entry'] = _IMG_STREAMER_REQUEST_ENTRY
DESCRIPTOR.message_types_by_name['img_streamer_reply_entry'] = _IMG_STREAMER_REPLY_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

img_streamer_request_entry = _reflection.GeneratedProtocolMessageType('img_streamer_request_entry', (_message.Message,), {
  'DESCRIPTOR' : _IMG_STREAMER_REQUEST_ENTRY,
  '__module__' : 'img_streamer_pb2'
  # @@protoc_insertion_point(class_scope:img_streamer_request_entry)
  })
_sym_db.RegisterMessage(img_streamer_request_entry)

img_streamer_reply_entry = _reflection.GeneratedProtocolMessageType('img_streamer_reply_entry', (_message.Message,), {
  'DESCRIPTOR' : _IMG_STREAMER_REPLY_ENTRY,
  '__module__' : 'img_streamer_pb2'
  # @@protoc_insertion_point(class_scope:img_streamer_reply_entry)
  })
_sym_db.RegisterMessage(img_streamer_reply_entry)


# @@protoc_insertion_point(module_scope)
