# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: macvlan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='macvlan.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmacvlan.proto\"1\n\x12macvlan_link_entry\x12\x0c\n\x04mode\x18\x01 \x02(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r'
)




_MACVLAN_LINK_ENTRY = _descriptor.Descriptor(
  name='macvlan_link_entry',
  full_name='macvlan_link_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='macvlan_link_entry.mode', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='macvlan_link_entry.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['macvlan_link_entry'] = _MACVLAN_LINK_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

macvlan_link_entry = _reflection.GeneratedProtocolMessageType('macvlan_link_entry', (_message.Message,), {
  'DESCRIPTOR' : _MACVLAN_LINK_ENTRY,
  '__module__' : 'macvlan_pb2'
  # @@protoc_insertion_point(class_scope:macvlan_link_entry)
  })
_sym_db.RegisterMessage(macvlan_link_entry)


# @@protoc_insertion_point(module_scope)
