# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timens.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timens.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ctimens.proto\"+\n\x08timespec\x12\x0e\n\x06tv_sec\x18\x01 \x02(\x04\x12\x0f\n\x07tv_nsec\x18\x02 \x02(\x04\"I\n\x0ctimens_entry\x12\x1c\n\tmonotonic\x18\x01 \x02(\x0b\x32\t.timespec\x12\x1b\n\x08\x62oottime\x18\x02 \x02(\x0b\x32\t.timespec'
)




_TIMESPEC = _descriptor.Descriptor(
  name='timespec',
  full_name='timespec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tv_sec', full_name='timespec.tv_sec', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tv_nsec', full_name='timespec.tv_nsec', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=59,
)


_TIMENS_ENTRY = _descriptor.Descriptor(
  name='timens_entry',
  full_name='timens_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='monotonic', full_name='timens_entry.monotonic', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boottime', full_name='timens_entry.boottime', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=134,
)

_TIMENS_ENTRY.fields_by_name['monotonic'].message_type = _TIMESPEC
_TIMENS_ENTRY.fields_by_name['boottime'].message_type = _TIMESPEC
DESCRIPTOR.message_types_by_name['timespec'] = _TIMESPEC
DESCRIPTOR.message_types_by_name['timens_entry'] = _TIMENS_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

timespec = _reflection.GeneratedProtocolMessageType('timespec', (_message.Message,), {
  'DESCRIPTOR' : _TIMESPEC,
  '__module__' : 'timens_pb2'
  # @@protoc_insertion_point(class_scope:timespec)
  })
_sym_db.RegisterMessage(timespec)

timens_entry = _reflection.GeneratedProtocolMessageType('timens_entry', (_message.Message,), {
  'DESCRIPTOR' : _TIMENS_ENTRY,
  '__module__' : 'timens_pb2'
  # @@protoc_insertion_point(class_scope:timens_entry)
  })
_sym_db.RegisterMessage(timens_entry)


# @@protoc_insertion_point(module_scope)
